{
  "name": "realdoor-backend",
  "type": "web",
  "runtime": "python",
  "region": "oregon",
  "branch": "main",
  "rootDir": "backend",
  "buildCommand": "pip install -r requirements.txt",
  "startCommand": "uvicorn app.main:app --host 0.0.0.0 --port $PORT",
  "envVars": [
    {
      "key": "CORS_ORIGINS",
      "value": "https://realdoor.vercel.app"
    },
    {
      "key": "ENCRYPTION_KEY",
      "value": "TlCmXcZsAz5XshJHttaJoWk-VbOMVBR6fC1vRmgKU84="
    }
  ]
}
